### ISSUE TITLE
Issues on macOS

### ISSUE THREAD

**Issue by mrcljx** [kosimst/FiraFlott#1]
1. When installing the Italic font on macOS, I get a warning about the "name table structure".
2. After installing it, FontBook claims that the Italic variant and the Regular variant are actually the same (i.e. it marks them as duplicates) and VSCode only renders FiraCode in faux-italic/oblique.

While I was unable to tackle (1), I was able to solve (2) by changing the TTF font files. I changed the PostScript name of both type faces (`FiraFlott` to `FiraFlott-Medium` and `FiraFlott-Italic`) and that seems to have fixed the issue.

**Comment by kosimst** [comment]
Thanks for the info, I will change 2. in the next few days. Unfortunately I don't have a Mac available, so I can't solve the first issue.

**Comment by mrcljx** [comment]
Thanks for building and sharing FiraFlott!

I'll let you know if I figure out what is causing that warning - sadly macOS isn't really providing more info there.

**Comment by kirklandspector** [comment]
+1 really hoping to use this but mac isn't happy about the duplicate fonts, wants to resolve them to one

**Comment by jastuccio** [comment]
I changed the post script, but still get the "multiple copies of this font are installed" error on my Mac

**Comment by tboetto** [comment]
I fixed this by editing the cursive font file in fontforge to have the same family & preferred family name as fira code, making it type italic, and then installing it alongside fira code.  When I edited the fira code type in font forge it removed the ligatures.

**Comment by duncanbb** [comment]
anyway someone can upload the changed font names? Don't really want to install font forge just to rename but I'd like to use the font!

**Comment by ghost** [comment]
@kosimst Did you do the way 2 (change name)? I get the latest ttf files and still have this issue on mac.
I don't know how to change with fontforge. Please guide me if you don't have time to do it in your source code

**Comment by igneosaur** [comment]
I've changed the names of the fonts in Font Forge to get rid of that "duplicate" error, I don't know enough about Font Forge to tackle the other issue yet. I think the italic font also needs it's boundaries adjusting, it maybe seems a bit big? Anyway this will help people get it installed on their Mac.

**Comment by ghost** [comment]
@igneosaur Thank you very much. I confirmed your `FiraFlott` works like a charm on Mac. Could you do the same for [Firicico](https://github.com/kosimst/Firicico)? 

Please create PR then @kosimst  can merge to his branch. Thank you both of you 💯 

@igneosaur One more private question :) Could you please guide me how to change names of fonts in FontForge?

**Comment by igneosaur** [comment]
@dungla4 No worries, yup PR has been created. I've also done one for [Firicico](https://github.com/kosimst/Firicico/pull/1).

Sure, open up the font file in FontForge and go to 'Element > Font Info' (Or `Ctrl` + `Shift` + `F`). Right there on the 'PS Names' panel you can change the 'Fontname', (keep the 'Family Name' the same). Click 'OK' (If it asks you something about changing the unique ID, choose to change it). Once you're ready to export select 'Files > Generate Fonts', make sure you have the font type 'TrueType' selected then hit 'Generate'.

**Comment by ghost** [comment]
@igneosaur Thank you very much. Your change in Firicico works well 🥇 and I can do follow your steps

**Comment by megaroeny** [comment]
> @dungla4 No worries, yup PR has been created. I've also done one for [Firicico](https://github.com/kosimst/Firicico/pull/1).
> 
> Sure, open up the font file in FontForge and go to 'Element > Font Info' (Or `Ctrl` + `Shift` + `F`). Right there on the 'PS Names' panel you can change the 'Fontname', (keep the 'Family Name' the same). Click 'OK' (If it asks you something about changing the unique ID, choose to change it). Once you're ready to export select 'Files > Generate Fonts', make sure you have the font type 'TrueType' selected then hit 'Generate'.

This worked 3 years later. Thanks! Surprised this hasn't been fixed until now. Silly...
